# Generated by Django 4.2.2 on 2023-06-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
